image:
  - Visual Studio 2017

init:
  - cmd: choco install octave.portable

build_script:
  - octave-cli playground.m
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config RELEASE
  - octave --no-gui --eval playground_mex

test_script:
  - octave --no-gui --eval playground_mex