language: cpp
#group: travis_latest

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
#    # windows build gives error:
#    # Cannot find file at '..\lib\octave.portable\tools\octave\bin\octave-cli.exe' (C:\ProgramData\chocolatey\lib\octave.portable\tools\octave\bin\octave-cli.exe). This usually indicates a missing or moved file.
#    - os: windows
#      before_install:
#      - choco install octave.portable
    - os: osx
      before_install:
        # otherwise there is an error when updating brew. TODO: remove it when brew fixes this issue
#        - HOMEBREW_NO_AUTO_UPDATE=1 brew install octave > /dev/null
        - brew install octave > /dev/null
    - os: linux
#      before_install:
#        - dpkg -L octave

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/mex -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_USING_OCTAVE=ON -DBUILD_USING_MATLAB=OFF
  - cmake --build . --config RELEASE
  - cmake --build . --config RELEASE --target install
  - ls
  # TODO: move it to cmake
  - cd ${TRAVIS_BUILD_DIR}/mex ;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      otool -L playground_octave_mex.mex ;
      install_name_tool -change @rpath/libTomatoLib.dylib @loader_path/libTomatoLib.dylib playground_octave_mex.mex ;
      otool -L playground_octave_mex.mex ;
    fi
  # Testing
  - cd ${TRAVIS_BUILD_DIR}
  - octave-cli tomatoMatlabInstall.m
  - ls
  - octave-cli tomatoMatlabExample1.m
  - octave-cli tomatoMatlabRunAllTests.m
  - ls mex

after_success:
  - export name=tomato_matlab_${TRAVIS_OS_NAME} # just a variable
  - cd ${TRAVIS_BUILD_DIR}/mex ;
  - zip -r ${name}.zip *
  - mkdir ${TRAVIS_BUILD_DIR}/deployment
  - cp ${TRAVIS_BUILD_DIR}/mex/${name}.zip ${TRAVIS_BUILD_DIR}/deployment/
  - ls ${TRAVIS_BUILD_DIR}/deployment
  - ls ${TRAVIS_BUILD_DIR}/mex

  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: releases
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: true
  file: deployment/*
  skip_cleanup: true
  on:
    tags: true
