language: cpp
group: travis_latest

addons:
  apt:
    packages:
      - octave

matrix:
  include:
    - os: windows
      language: sh
      before_install:
      - choco install octave.portable
    - os: osx
      before_install:
      -  brew install octave > /dev/null
    - os: linux
      before_install:
      - dpkg -L octave

script:
#  - octave --no-gui --eval playground.m
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then C:\ProgramData\chocolatey\bin\octave.exe ${TRAVIS_BUILD_DIR}/playground.m ; fi
  - octave-cli ${TRAVIS_BUILD_DIR}/playground.m
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config RELEASE
  - ls
  - octave --no-gui --eval playground_mex.mex # octave-cli not working if mex is passed as an argument
