language: cpp
group: travis_latest

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
    - os: windows
      language: sh
      before_install:
      - choco install octave.portable
#      - choco install octave.install
    - os: osx
      before_install:
      -  brew install octave > /dev/null
    - os: linux
      before_install:
      - dpkg -L octave
#      - find / -name "liboctave.so"
#      - find / -name "liboctinterp.so"

script:
#  - octave --no-gui --eval playground.m
  - dir ${TRAVIS_BUILD_DIR}
  - octave-cli playground.m
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config RELEASE
  - ls
  - octave --no-gui --eval playground_mex # octave-cli not working if mex is passed as an argument
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - ls octave
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ${TRAVIS_BUILD_DIR}/octave/mingw64/bin/octave-cli.exe ${TRAVIS_BUILD_DIR}/playground.m ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then C:/ProgramData/chocolatey/bin/octave.exe ${TRAVIS_BUILD_DIR}/playground.m ; fi
  - ls /usr/include/
