language: cpp
group: travis_latest

addons:
  apt:
    packages:
      - octave

matrix:
  include:
    - os: linux
    - os: windows
      language: sh
      before_install:
         - choco install octave.portable
    - os: osx
      before_install:
      -  brew install octave > /dev/null

script:
  - octave --no-gui --eval playground.m
  - octave-cli ${TRAVIS_BUILD_DIR}/playground.m
  # - octave-cli playground.m
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config RELEASE
