language: cpp
#group: travis_latest

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
#    # windows build gives error:
#    # Cannot find file at '..\lib\octave.portable\tools\octave\bin\octave-cli.exe' (C:\ProgramData\chocolatey\lib\octave.portable\tools\octave\bin\octave-cli.exe). This usually indicates a missing or moved file.
#    - os: windows
#      before_install:
#      - choco install octave.portable
    - os: osx
      before_install:
        # otherwise there is an error when updating brew. TODO: remove it when brew fixes this issue
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install octave > /dev/null
    - os: linux
#      before_install:
#        - dpkg -L octave

script:
  - octave-cli playground.m
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DBUILD_SHARED_LIBS=ON
  - cmake --build . --config RELEASE
  - cmake --build . --config RELEASE --target install
  - ls
  # Testing
  - octave --no-gui --eval playground_octave_mex # octave-cli not working if mex is passed as an argument
  - cd ${TRAVIS_BUILD_DIR}
  - octave-cli playground_mex.m
  - ls install

after_success:
  - export name=tomato_matlab_${TRAVIS_OS_NAME} # just a variable
  - cd ${TRAVIS_BUILD_DIR}/install
  - zip -r ${name}.zip *
  - mkdir ${TRAVIS_BUILD_DIR}/deployment
  - cp ${TRAVIS_BUILD_DIR}/install/${name}.zip ${TRAVIS_BUILD_DIR}/deployment/
  - ls ${TRAVIS_BUILD_DIR}/deployment
  - ls ${TRAVIS_BUILD_DIR}/install
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: releases
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: ON
