language: cpp
group: travis_latest

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
#    # windows build gives error:
#    # Cannot find file at '..\lib\octave.portable\tools\octave\bin\octave-cli.exe' (C:\ProgramData\chocolatey\lib\octave.portable\tools\octave\bin\octave-cli.exe). This usually indicates a missing or moved file.
#    - os: windows
#      before_install:
#      - choco install octave.portable
    - os: osx
      before_install:
      -  brew install octave > /dev/null
    - os: linux
      before_install:
      - dpkg -L octave

script:
  - octave-cli playground.m
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install
  - cmake --build . --config RELEASE
  - ls
  # Testing
  - octave --no-gui --eval playground_octave_mex # octave-cli not working if mex is passed as an argument
  - cd ${TRAVIS_BUILD_DIR}
  - octave-cli playground_mex.m
  - ls install
