language: cpp
group: travis_latest

addons:
  apt:
    packages:
      - octave

matrix:
  include:
    - os: linux
    - os: windows
      language: sh
      before_install:
        - choco install octave.portable
        # - choco install octave
    - os: osx
      before_install:
      -  brew install octave > /dev/null

script:
  - octave-cli playground.m
  # - octave-cli playground.m
